version: "3.9"
services:
    environment:
        build: .
        container_name: product_manager_application
        volumes:
            - ../:/var/www/html
        environment:
            RABBITMQ_SERVER: rabbitmq
            DB_HOST: mysql
        depends_on:
            - rabbitmq
            - mysql
            - nginx
        links:
            - rabbitmq
            - mysql
            - nginx
    nginx:
        image: nginx:1.21.6
        container_name: product_manager_nginx
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html
            - ./config/nginx/application.conf:/etc/nginx/conf.d/default.conf
    rabbitmq:
        image: rabbitmq:3-management
        container_name: product_manager_rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
    mysql:
        image: mysql:5.7
        container_name: product_manager_mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        expose:
            - '3306'
        environment:
            MYSQL_DATABASE: 'product_manager'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./init:/docker-entrypoint-initdb.d
